import type { RouteItem } from "./routeTypes";

export const userRoutes: RouteItem[] = [
  {
    path: "/",
    component: "Home",
    exact: true,
    layout: "main",
    filePath: "user/cover/",
  },
  {
    path: "/register",
    component: "SignUp",
    exact: true,
    layout: "none",
    filePath: "user/auth/",
  },
  {
    path: "/verify-email",
    component: "VerifyEmail",
    exact: true,
    layout: "auth", //auth,main,none,
    filePath: "user/auth/",
  },
  {
    path: "/login",
    component: "LoginPage",
    layout: "auth",
    filePath: "user/auth/",
  },
  {
    path: "/forget-password",
    component: "ForgetPassword",
    layout: "auth",
    filePath: "user/auth/",
  },
  {
    path: "/reset-password",
    component: "ResetPassword",
    exact: true,
    protected: false,
    layout: "auth",
    filePath: "user/auth/",
  },
  {
    path: "/projects",
    component: "Dashboard",
    exact: true,
    protected: true,
    layout: "app",
    filePath: "user/project/",
  },
  {
    path: "/success",
    component: "AuthSuccess",
    layout: "none",
    filePath: "user/auth/",
  },

  {
    path: "/projects/:projectId",
    component: "ProjectDetail",
    exact: true,
    protected: true,
    layout: "app",
    filePath: "user/project/",
  },
  {
    path: "/upgrade",
    component: "UpgradePlanPage",
    layout: "app",
    protected: true,
    filePath: "user/upgrade/",
  },
  {
    path: "/payment/success",
    component: "PaymentSuccess",
    layout: "main",
    protected: true,
    filePath: "user/upgrade/",
  },
  {
    path: "/payment/failed",
    component: "PaymentFailed",
    layout: "main",
    protected: true,
    filePath: "user/upgrade/",
  },
  {
    path: "/user/profile",
    component: "UserProfile",
    layout: "app",
    protected: true,
    filePath: "user/profile/",
  },
  {
    path: "/invite",
    component: "InvitePage",
    layout: "auth",
    protected: false,
    filePath: "user/project/",
  },
  // {
  //   path: '/',
  //   component: 'Dashboard',
  //   exact: true,
  //   protected: true,
  // },
];

export const adminRoutes: RouteItem[] = [
  // {
  //   path: "/admin/profile",
  //   component: "UserProfiles",
  //   layout: "admin",
  //   protected: true,
  // },
  {
    path: "/admin/login",
    component: "SignIn",
    layout: "admin",
    filePath: "admin/AuthPages/",
  },
  {
    path: "/admin/dashboard",
    component: "Home",
    layout: "admin",
    protected: true,
    filePath: "admin/Dashboard/",
  },
  {
    path: "/admin/users",
    component: "UsersManagementPage",
    layout: "admin",
    protected: true,
    filePath: "admin/Users/",
  },
  {
    path: "/admin/plan",
    component: "PlanManagementPage",
    layout: "admin",
    protected: true,
    filePath: "admin/Plan/",
  },
  {
    path: "admin/forgot-password",
    component: "Home",
    layout: "admin",
    protected: true,
    filePath: "admin/Dashboard/",
  },
];
